name: Build Mesa AAR

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Native Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build python3-pip python3-setuptools python3-mako libxrandr-dev libxxf86vm-dev libxcb-glx0-dev gettext bzip2 bison flex pkg-config

      - name: Grant Execute Permissions to Packager Scripts
        run: |
          chmod +x *.sh

      - name: Execute Mesa Package Generation
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk-bundle
        run: |
          ./aargen_mesa.sh
          ./create_aar.sh

      - name: Upload Compiled Mesa AAR
        uses: actions/upload-artifact@v4
        with:
          name: mesa-aar
          path: |
            **/*.aar
          if-no-files-found: error
          
